# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-10 22:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('phone', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message=b'Invalid phone number', regex=b'^.{12}$')])),
                ('street', models.CharField(max_length=70)),
                ('house', models.CharField(blank=True, max_length=5)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
