# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-08 17:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message=b'Invalid phone number', regex=b'^.{4}$')])),
                ('street', models.CharField(max_length=70)),
                ('house', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=5)),
            ],
        ),
    ]
