# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-15 18:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('discount', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='OnlineOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=70)),
                ('delivery_address', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message=b'Invalid phone number', regex=b'^.{12}$')])),
                ('net_bill', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('net_discount', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('payment_option', models.CharField(choices=[(b'1', b'COD'), (b'2', b'NET_BANKING')], max_length=1)),
                ('placed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[(b'1', b'PLACED'), (b'2', b'READY'), (b'3', b'Out for Delivery'), (b'4', b'DEVLIVERED'), (b'5', b'CANCELLED')], default=b'1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=1)),
                ('price', models.FloatField()),
                ('discount', models.FloatField(default=0.0)),
                ('qty', models.IntegerField(default=1)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Item')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.OnlineOrder')),
            ],
        ),
    ]
