# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-18 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_onlineorder_orderdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='currency_code',
            field=models.CharField(default=b'EUR', max_length=3),
        ),
    ]
